spring:
  #前后端模板
  thymeleaf:
    cache: false
  #连接数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver   #驱动
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/trading?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    #配置数据源信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMills: 60000
    minEvictableIdleTimeMills: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filter:
      stat:
        enabled: true
        log-slow-sql: true
      wall:
        enabled: true
    #security提供配置内容
    security:
      user:
        name: admin         #用户名
        password: 123456    #密码
  #国际化配置文件路径
  messages:
    basename:i18n

additional-paths: src/main/java  #开启实时热部署的重启目录
freemarker:
  cache: false                   #页面不加载缓存，加载即生效

server:
  port: 8080

  #mybatis相关配置
mybatis:
  type-aliases-package: com.li.demo.entity  #mapper接口存放的目录
  configuration:
    map-underscore-to-camel-case: true    #开启驼峰命名
  mapper-locations: classpath:mappers/*.xml  #映射xml文件，建议写在resources目录下




